### ISSUE TITLE
Property-based tests

### ISSUE THREAD

**Issue by nomeata** [dfinity-lab/hs-dfinity-radix-tree#13]
It would be great to have some property-based tests (i.e. QuickCheck) – they are just so much more effective than unit tests. Maybe a good task for me to get to know the code better.

**Comment by taktoa** [comment]
+1, but I recommend [Hedgehog](https://hackage.haskell.org/package/hedgehog) over QuickCheck.

**Comment by enzoh** [comment]
+2. It wraps a key-value store, so one obvious property test is that if you put something into the tree, then you should be able to get it out. Also, if you delete everything you put in, you should get exactly the same state root.

**Comment by enzoh** [comment]
I vote QuickCheck, but if you want to use Hedgehog, then go for it.

**Comment by enzoh** [comment]
Actually, I take that back! If we're using [`tasty-hunit`](http://hackage.haskell.org/package/tasty-hunit) for the unit tests as mentioned in [another issue](https://github.com/dfinity-lab/hs-dfinity-radix-tree/issues/13), then we should use [`tasty-quickcheck`](http://hackage.haskell.org/package/tasty-quickcheck). I've [`tasty`](http://hackage.haskell.org/package/tasty) for several years. It's a great framework. We should standardize on it.

**Comment by infinity0** [comment]
+1 for tasty, we're using it in p2p.git already too

**Comment by nomeata** [comment]
+1 for tasty as well.

**Comment by taktoa** [comment]
There is a [tasty-hedgehog](http://hackage.haskell.org/package/tasty-hedgehog) fwiw.
